- name: installation du jdk8
  package: name=openjdk-8-jdk-headless state=present

- name: creation du groupe "tomee"
  group: name=tomee

- name: creation de l'utilisateur "tomee"
  user: name=tomee group=tomee home=/home/tomee createhome=yes
  become: True
  become_method: sudo

- name: creation dossier
  file: path=/opt/tomee state=directory
  
- name: changer proprietaire du dossier
  file: path=/opt/tomee owner=tomee group=tomee state=directory recurse=yes

- name: telechargement de Tomee
  get_url: url=http://repo.maven.apache.org/maven2/org/apache/tomee/apache-tomee/7.0.3/apache-tomee-7.0.3-plus.tar.gz dest=/opt/tomee/apache-tomee-7.0.3-plus.tar.gz

- name: extraire l'archive
  shell: /bin/tar xvzf /opt/tomee/apache-tomee-7.0.3-plus.tar.gz -C /opt/tomee/ --strip-components=1

- name: mise a jour des permissions
  shell: cd/opt/tomee
  shell: chgrp -R tomee /opt/tomee
  shell: chmod -R g+r conf
  shell: chmod g+x conf
  shell: chown -R tomee webapps/ work/ temp/ logs/

- name: creation du fichier system.d
  shell: echo "[Unit] \nDescription=Apache tomee Web Application Container \n
  After=network.target \n[Service] \nType=forking \nEnvironment=JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre \nEnvironment=CATALINA_PID=/opt/tomee/temp/tomee.pid \nEnvironment=CATALINA_HOME=/opt/tomee \nEnvironment=CATALINA_BASE=/opt/tomee \nEnvironment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC' \nEnvironment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom' \nExecStart=/opt/tomee/bin/startup.sh \nExecStop=/opt/tomee/bin/shutdown.sh \nUser=tomee \nGroup=tomee \nUMask=0007 \nRestartSec=10 \nRestart=always \n[Install] \nWantedBy=multi-user.target \n" > /etc/systemd/system/tomee.service